### PR TITLE
Remove unnecessary aliasing in df.castToLong helper

### LINKED ISSUE #773: Planner hangs for TPC-H Query 14
```
MATCH
  (l:Lineitem)-[:HAS_PART]->(p:Part)
WHERE
  l.l_shipdate >= 809913600
  AND l.l_shipdate < 812505600
RETURN
  100.0 * SUM(
  CASE
    WHEN p.p_type =~ 'PROMO.*' THEN l.l_extendedprice * (1 - l.l_discount)
    ELSE 0.0
    END
  ) /
  SUM(l.l_extendedprice * (1 - l.l_discount)) AS promo_revenue
```

Relational planner runs through. However, after calling `df.show` or `df.explain`, the program hangs, one thread is running (probably catalyst) and the program crashes eventually (no exception).

A workaround is an additional `WITH` clause.

```
MATCH
  (l:Lineitem)-[:HAS_PART]->(p:Part)
WHERE
  l.l_shipdate >= 809913600
  AND l.l_shipdate < 812505600
WITH
  SUM(
  CASE
    WHEN p.p_type =~ 'PROMO.*' THEN l.l_extendedprice * (1 - l.l_discount)
    ELSE 0.0
    END
  ) /
  SUM(l.l_extendedprice * (1 - l.l_discount)) AS promo_revenue
RETURN promo_revenue * 100.00
```

### PR DESCRIPTION
**Pull request by s1ck**
For TPC-H Query 14 the additional aliasing resulted in an issue within the `InferFiltersFromConstraints` rewriter in Catalyst. Will try to reproduce the bug with plain dataframes and report to Spark Jira.

* fixes #773

### CODE REVIEW

File: spark-cypher/src/main/scala/org/opencypher/spark/impl/table/SparkTable.scala [hunk 1]
```diff
@@ -373,7 +373,7 @@ object SparkTable {
     }
 
     def safeRenameColumns(renamings: Map[String, String]): DataFrame = {
-      if (renamings.forall { case (oldColumn, newColumn) => oldColumn == newColumn }) {
+      if (renamings.isEmpty || renamings.forall { case (oldColumn, newColumn) => oldColumn == newColumn }) {
```
Comment (pstutz) [inline spark-cypher/src/main/scala/org/opencypher/spark/impl/table/SparkTable.scala]: Can't `renamings.isEmpty || ' be removed without changing the semantic?

Comment (s1ck) [reply spark-cypher/src/main/scala/org/opencypher/spark/impl/table/SparkTable.scala]: You're right. `Seq.forall` already returns `true` if the `Seq` is empty.
